In [4]:
import numpy as np

DataTypes and Attributes

In [5]:
a1 = np.array([1, 2, 3])

In [6]:
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

a3= np.array([[[1,2,3],
              [4,5,6],
             [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1.shape

(3,)

In [13]:
a2.shape,type(a2)

((2, 3), numpy.ndarray)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.size, a2.size,a3.size

(3, 6, 18)

In [17]:
import pandas as pd

In [18]:
df = pd.Dataframe(a2)
df

AttributeError: module 'pandas' has no attribute 'Dataframe'

## Creating Array

In [ ]:
sample_array = np.array([1,2,3])
sample_array

In [ ]:
sample_array.dtype

In [ ]:
ones = np.ones([2,3])

In [ ]:
ones

In [ ]:
type(ones)

In [ ]:
zeros = np.zeros([2,3])

In [ ]:
range_array = np.arange(0,10,2)

In [ ]:
range_array

In [ ]:
random_array= np.random.randint (0, 10, size=(3,5))
random_array

In [ ]:
random_array.size

In [ ]:
random_array.shape

random_array_2 = np.random.rand([5,3])
random_array_2 

In [ ]:
random_array_2 

a2

a3

In [ ]:
a1

In [ ]:
a2

## 

In [ ]:
a3

In [ ]:
a1*a2

In [ ]:
np.square(a1)

In [ ]:
a1/a2

In [ ]:
a1//a2

In [ ]:
a1%1

## 

In [ ]:
a2%2

In [ ]:
a1-a2

In [ ]:
a1--a2

In [ ]:
a1*a2

In [ ]:
np.dot(a1 , a2)

In [ ]:
a1.reshape

# reshape

In [ ]:
a1.T

In [ ]:
a1.T.shape, a2.shape

## 

In [19]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [20]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
np.dot(a1, a2.T)

array([14.9, 33.5])

In [22]:
a1.shape, a2.T.shape

((3,), (3, 2))

In [23]:
a1.reshape

<function ndarray.reshape>

In [24]:
a1

array([1, 2, 3])

In [25]:
a1.reshape(1,2,3)

ValueError: cannot reshape array of size 3 into shape (1,2,3)

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
np.dot(a2.T, a3)

ValueError: shapes (3,2) and (2,3,3) not aligned: 2 (dim 1) != 3 (dim 1)

In [28]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [29]:
np.dot(a2, a3.T)

array([[[ 32.1,  88.8],
        [ 38.4,  95.1],
        [ 44.7, 101.4]],

       [[ 69.5, 209. ],
        [ 85. , 224.5],
        [100.5, 240. ]]])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
sales_amount = np.array([[2, 7, 1],
                         [9, 4, 16],
                         [11, 14, 18],
                         [13, 13, 16],
                        [15, 18, 9]])

In [32]:
sales_amount

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [33]:
import pandas as pd

In [34]:
weekly_sales = pd.DataFrame(sales_amount, 
                           index= ["Mon", "Tues", "Wed", "Thur", "Fri"],
                           columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               2              7              1
Tues              9              4             16
Wed              11             14             18
Thur             13             13             16
Fri              15             18              9

In [35]:
prices = np.array([10, 8, 12])

In [36]:
prices

array([10,  8, 12])

In [37]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["prices"],
                            columns= ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
prices             10              8             12

In [38]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([ 88, 314, 438, 426, 402])

In [39]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               2              7              1
Tues              9              4             16
Wed              11             14             18
Thur             13             13             16
Fri              15             18              9

In [40]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [42]:
weekly_sales.T.shape

(3, 5)

In [43]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thur  Fri
prices   88   314  438   426  402

In [45]:
weekly_sales["Total ($)"]= daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               2              7              1         88
Tues              9              4             16        314
Wed              11             14             18        438
Thur             13             13             16        426
Fri              15             18              9        402

## Comparison Operator

In [46]:
a1

array([1, 2, 3])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [49]:
a2>a1

array([[False, False,  True],
       [ True,  True,  True]])

In [50]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

In [51]:
a1<5

array([ True,  True,  True])

In [52]:
a2>5

array([[False, False, False],
       [False, False,  True]])

In [57]:
a1==a2

array([[ True,  True,  True],
       [ True,  True,  True]])

## Sorting Arrays

In [58]:
random_array=np.random.randint(10, size =(3,5))
random_array

array([[0, 3, 7, 1, 4],
       [8, 8, 8, 7, 2],
       [5, 6, 6, 0, 3]])

In [60]:
np.sort(random_array)

array([[0, 1, 3, 4, 7],
       [2, 7, 8, 8, 8],
       [0, 3, 5, 6, 6]])

In [61]:
np.argsort(random_array)

array([[0, 3, 1, 4, 2],
       [4, 3, 0, 1, 2],
       [3, 4, 0, 1, 2]], dtype=int64)

In [62]:
a1

array([[ 2. ,  4. ,  6.6],
       [ 8. , 10. , 13. ]])

In [63]:
np.argsort(a1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

## Numpy in Action

In [72]:
<img src = "images/panda.png"/>

SyntaxError: invalid syntax (2084924934.py, line 1)